- u-boot: back to version 2021.04 because error on buildserver ...
ecdsa-libcrypto.c:(.text+0x65d): undefined reference to `EC_POINT_get_affine_coordinates'