Revert "- bash: bump version to 5.1.16" because of broken hd2-build
random.c:188:1: error: static declaration of ‘getrandom’ follows non-static declaration
 getrandom (buf, len, flags)
 ^~~~~~~~~
In file included from random.c:26:0:
/home/vanhofen/ni/buildsystem/cross/arm-linux-3.10.93/arm-cortex-linux-uclibcgnueabi/sys-root/usr/include/sys/random.h:27:12: note: previous declaration of ‘getrandom’ was here
 extern int getrandom(void *__buf, size_t count, unsigned int flags)
            ^~~~~~~~~

This reverts commit ea817e3f252d69c21757270bbcd4c7c4d6b2a079.